### ISSUE TITLE
Question: Local development

### ISSUE THREAD

**Issue by mcgilly17** [redyf/Neve#106]
Hey @redyf 

I hope you don't mind me posting this here. 

I was hoping you might help me improve my workflow for developing a standalone nix config. 

So far the only way that I can develop while maintaining a nix-config on my machines is below. Is it the same workflow you use?

1. Active development on standalone nixvim configs in a cloned repo on my local.
2. Run `nix run` to check that it's working 
3. Commit and push to GitHub
4. Add standalone nixvim configs as a flake into my nix-config for my machines
5. Run `nix flake update` on nix-configs to pull in latest nixvim configs
6. Switch to new version of the nix configs flake. 

I feel like I might be missing a trick with nix develop and build on my local. Can you spare any wisdom, please?

**Comment by redyf** [comment]
> Hey @redyf
> 
> I hope you don't mind me posting this here.
> 
> I was hoping you might help me improve my workflow for developing a standalone nix config.
> 
> So far the only way that I can develop while maintaining a nix-config on my machines is below. Is it the same workflow you use?
> 
>     1. Active development on standalone nixvim configs in a cloned repo on my local.
> 
>     2. Run `nix run` to check that it's working
> 
>     3. Commit and push to GitHub
> 
>     4. Add standalone nixvim configs as a flake into my nix-config for my machines
> 
>     5. Run `nix flake update` on nix-configs to pull in latest nixvim configs
> 
>     6. Switch to new version of the nix configs flake.
> 
> 
> I feel like I might be missing a trick with nix develop and build on my local. Can you spare any wisdom, please?

Those are the exactly same steps I do too

**Comment by mcgilly17** [comment]
Thanks!
