### ISSUE TITLE
Question on the vertical line that appears when editing a file

### ISSUE THREAD

**Issue by vinylen** [redyf/Neve#107]
Hi,

I've been trying out Neve for the day, and i love it, but i can't figure out what is adding the vertical line when editing files?

![image](https://github.com/user-attachments/assets/b6148c78-e266-4052-907b-19215327bfb5)

What is that and how can i remove it? :) 

Thanks again for Neve!

**Comment by redyf** [comment]
> Hi,
> 
> I've been trying out Neve for the day, and i love it, but i can't figure out what is adding the vertical line when editing files?
> 
> ![image](https://private-user-images.githubusercontent.com/98466471/362259871-b6148c78-e266-4052-907b-19215327bfb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NjM3NzUsIm5iZiI6MTcyNDk2MzQ3NSwicGF0aCI6Ii85ODQ2NjQ3MS8zNjIyNTk4NzEtYjYxNDhjNzgtZTI2Ni00MDUyLTkwN2ItMTkyMTUzMjdiZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIwMzExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YzFkN2E3ZTU5ZTNjNzdjMDFmZjBlN2E1NzEzMTZhNjMwODJhZGNlN2RhZjgxNWEyYjhmYTQ1YWRjMGVmOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_XtilzvPXWXoDh0r9Hlmqm9ZAaP4ZzRcavv7-tEBEc)
> 
> What is that and how can i remove it? :)
> 
> Thanks again for Neve!

Hello, I'm glad you're enjoying it :smile:.
Just to make sure, do you mean this line?
![image](https://github.com/user-attachments/assets/ebea7d58-d793-4009-9f80-88de4c4f51b0)

**Comment by vinylen** [comment]
Yes thank you, it was the colorcolumn i was referring to. 

Thanks again!
