### ISSUE TITLE
Clearer Post-Installation Instructions

### ISSUE THREAD

**Issue by kimjongbing** [redyf/Neve#109]
**Currently**
It is unclear how (for a new-ish user) to modify Neve.
1. You input the flake 
2. You import it into your config (like home.nix)
3. You have stock Neve
But it is not very clear how to modify something like keybinds.

**Solution**
Have somewhat basic steps post-installation, specifically for something common like modifying some configs.

**Comment by kimjongbing** [comment]
Relevant #73

**Comment by redyf** [comment]
Great suggestion, I'll add it to the readme :+1:

**Comment by redyf** [comment]
Would love to see some feedback, let me know if I should change something in the guide :smile:

**Comment by kimjongbing** [comment]
> Would love to see some feedback, let me know if I should change something in the guide 😄

I think the changes are clear enough :smile:  
Maybe if people ask a lot of the same thing in the future that could inform a new change

Thank you again! Love your work
