### ISSUE TITLE
Difficulty with auto-formatting/line breaks

### ISSUE THREAD

**Issue by jee-mj** [redyf/Neve#110]
# Difficulty with auto-formatting/line breaks using conform

### Background

I came across Neve when trying to learn vim from theprimeagen, overriding my previous config pulled from craftzdog. You can track this gradual process [in my dotFiles](https://github.com/jee-mj/dotFiles). I thought I'd have to modify my `./home/neovim.nix` but then I remembered something from a past stream that `Neve` exists and is awesome. So I tried it out and I'm basically very satisfied with this configuration. Still working on integrating my own themes to this, which I'll get working properly eventually.

Anyway, I am making this issue because I couldn't send you a friend request to message you on discord. It might be better if you create a server for this config if it's within your allowances.

### Problem

I can't use gqap to split lines at a given column (e.g. 80). I noticed in `sets.nix` that we have `conform`, but nothing happens when I type `VG cF`, and if I type `VG cf` it deletes everything and replaces it with 'if' or 'f'.

### Configuration

You can find my nvim config [here](https://github.com/jee-mj/tree/testing).
I'm trying to format the default `page.tsx` from nextjs@latest.
Using devenv with the following:
```nix
  languages.go.enable = true;
  languages.javascript = {
    enable = true;
    npm.enable = true;
    yarn.enable = true;
  };
  ```

## Thanks

**Comment by redyf** [comment]
Hello jee, thanks for giving Neve a try!
Do you have prettierd or prettier installed? Conform will use them for formatting the selected code block, and on save aswell.
Your neovim config doesn't seem to be available at the moment so I can't check, but let me know if it works. My DMs on Discord are open now btw, thanks for pointing that out.
