### ISSUE TITLE
Add Codeium plugin

### ISSUE THREAD

**Issue by SolidRhino** [redyf/Neve#116]
Is it possible to add the Codeium plugin? To add more AI support options.

**Comment by redyf** [comment]
Sorry for the delay, life gets in the way sometimes and I wanted to try codeium before adding it... It's disabled by default but you can toggle it in ```config/completion/default.nix```. More details in https://github.com/redyf/Neve/commit/fa836860e7865e8b44236e475617c498a60b450c, thanks for giving Neve a try! :100:
