### ISSUE TITLE
Toggling autoformat with conform does not work.

### ISSUE THREAD

**Issue by rollf** [redyf/Neve#118]
Hi, 

I believe autoformat is always on, even when using `:FormatToggle[!]`. 

Adding this to my lua config fixes this:

```lua
require("conform").setup({
  format_on_save = function(bufnr)
    -- Disable with a global or buffer-local variable
    if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
      return
    end
    return { timeout_ms = 500, lsp_format = "fallback" }
  end,
})
```

This is just copied and pasted from [here](https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#command-to-toggle-format-on-save) and I think this should probably just be added [here](https://github.com/redyf/Neve/blob/c9a358731029ba75d17924865ddaa0d057be5a31/config/lsp/conform.nix#L18).

**Comment by redyf** [comment]
Thank you! :smiley:
