### ISSUE TITLE
How to change options?

### ISSUE THREAD

**Issue by retchohrips** [redyf/Neve#73]
Very sorry, I feel like I am missing something obvious here... So, after adding Neve into my flake, I'm able to install it, everything is working fine. However, I want to change a few options. The README implies that changing the options is easy, but then refers to files inside of this repo, which use nixvim, so I assumed I could just change the nixvim options in home-manager, but `programs.nixvim` in home-manager seems to have no effect, and there does not seem to be another way, like `programs.neve`, to easily change these. Again, I feel like there is an immediate answer right in front of me that I am just not seeing, so my apologies for posting.

**Comment by redyf** [comment]
Hello retchoh, thanks for giving Neve a try!

I suggest forking the repo, making the changes in there and then add it as an input in your flake.nix file. That should do it :+1:
