### ISSUE TITLE
How can I install this systemwide in a distro other than NixOS?

### ISSUE THREAD

**Issue by amalgame21** [redyf/Neve#74]
I am using Arch linux, and I came across nixvim and this repo, it seems very nice to configure neovim in nix way.
I know I can run `nix run ` to test this repo, but how can I install it systemwide?
I cannot find any tutorials that install flake in distros other that NixOS.
Thanks!

**Comment by redyf** [comment]
Hello amalgame, unfortunately I've never tried nix on other distros so I'm not sure how you'd do that. But there is a pretty good guide in this website: https://tech.aufomm.com/my-nix-journey-use-nix-with-ubuntu/, even though it's for Ubuntu I believe it might help you.
