### ISSUE TITLE
fix this issue.

### ISSUE THREAD

**Issue by sachinchaudhary1808** [redyf/Neve#77]
![image](https://github.com/redyf/Neve/assets/138745629/d91756b7-aeb2-47f6-996e-622ae4ef5c5d)

**Comment by redyf** [comment]
Hello, thanks for reporting this error. Looks like there were many refactors in NixVim so those none-ls sources were removed. Just tried nix run on my end and it worked, however many traces will still show up. I'll update all of it when I get some free time. Thanks again :+1:
