### ISSUE TITLE
Make Neve modular

### ISSUE THREAD

**Issue by tuxiqae** [redyf/Neve#96]
Allow users to customize their Neve experience using Nix options

**Comment by redyf** [comment]
Hello tuxi, could you provide an example?

**Comment by tuxiqae** [comment]
Hi!
For example, since I don't see a need to use Discord or WakaTime I just cloned the repo, edit the relevant files in order to disable those features, and now I use this fork instead of `redyf/Neve`

In Nix you can create a module, and within it define options (using `mkOption`), the consumers of your flake Neve will be able to enable and disable specific features by toggling on specific features.

For example: https://nix.dev/tutorials/module-system/a-basic-module/index.html

For example, the NixOS module`services.tailscale`:
- [Options](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=services.tailscale.)
- [Code](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/networking/tailscale.nix)

**Comment by redyf** [comment]
That's an amazing idea, I'll take a deeper look into it. Thanks! 😄

**Comment by rolfschr** [comment]
FYI, this is how I approached this: I used the Neve flake with a custom config that I provide using `nixvimExtend`. This allows me to fully customize to my needs (including deactivation) while still following upstream.

```nix
# flake.nix
inputs.neve.url = "github:redyf/Neve";
...
myConfig = {
    extraPackages = with pkgs; [
      alejandra # nix formatter
      ...
    ];

    extraPlugins = with pkgs.vimPlugins; [
      eyeliner-nvim
      ...
    ];

    plugins = {
      alpha.enable = pkgs.lib.mkForce false; # welcome screen
      copilot-lua.enable = pkgs.lib.mkForce false;
      indent-blankline.enable = pkgs.lib.mkForce false; # indentation guides
      lint = {
        lintersByFt = {
          sh = ["shellcheck"];
     ...
    };
    extraConfigLua = ''
      require("cmp").setup {
       ...
    };
    keymaps = ...
};

...
myNeve = neve.packages."${system}".default.nixvimExtend { config = myConfig;};↲``

**Comment by redyf** [comment]
I had no idea you could do that haha, really cool :fire:

**Comment by glwbr** [comment]
Hi! I couldn't find another way to contact you through your profile, so I'm using this issue for discussion. I'm currently working on my own NixVim configuration, taking inspiration from Neve and other projects. One challenge I encountered is the need for certain packages to be installed on the host system, such as prettierd, golines, gopls, ruff, etc., to get them working in Nix/Neovim.

I'm trying to solve this by creating a fully independent configuration that automatically enables LSPs, completions, and snippets based on the languages installed on the system. For example, if a user has Go installed, then the Go LSP and related features will be enabled; the same would apply for Node.js, Python, and other languages.

Have you considered this approach? The methods used by @tuxiqae and @rolfschr seem like a perfect example of how to achieve this. Currently, I have a basic initial configuration set up for this purpose.

![Nix Code Example](https://github.com/user-attachments/assets/b37e905c-c5db-4106-9b66-f3008270377a)

Here's the link to my config:
https://github.com/glwbr/corgix

**Comment by redyf** [comment]
I've never considered this approach, but it does look interesting. Usually what I do is just use a nix flake + direnv. It's great to see there are so many ways available to setup an environment with nix.

**Comment by redyf** [comment]
> Hey @redyf, would you be fine with providing a bit of documentation on how to use #111 now that it's been merged ? Thank you for the awesome work.

Sure! I'll add it asap, it might seem complex but it's really not. I'll explain it in the readme :+1: Thanks for supporting Neve.

**Comment by redyf** [comment]
https://github.com/redyf/Neve/commit/8e39471736f6f6070c1dfbf74945ff3a5936f15d
@Shyrogan let me know what you think :smile:

**Comment by Shyrogan** [comment]
> [8e39471](https://github.com/redyf/Neve/commit/8e39471736f6f6070c1dfbf74945ff3a5936f15d) @Shyrogan let me know what you think 😄

I think an example that uses `nixvimExtend` extend would be better. Using this basically allows us to override your settings without touching the sources of Neve directly, that would be lovely

I'll try to write one myself on my free-time and comment it here

**Comment by redyf** [comment]
> > [8e39471](https://github.com/redyf/Neve/commit/8e39471736f6f6070c1dfbf74945ff3a5936f15d) @Shyrogan let me know what you think 😄
> 
> I think an example that uses `nixvimExtend` extend would be better. Using this basically allows us to override your settings without touching the sources of Neve directly, that would be lovely
> 
> I'll try to write one myself on my free-time and comment it here

Indeed, that sounds good. I'll be kinda busy with work and some exams in the next few days so a PR would be very much appreciated for that one. Thanks for the suggestion 🙂

**Comment by Shyrogan** [comment]
@redyf That required small changes, PR is in #113
