### ISSUE TITLE
TODO: Move general keys to Which-key

### ISSUE THREAD

**Issue by mcgilly17** [redyf/Neve#99]
Hey @redyf 

I saw the TODO in keymaps.nix, I just moved my general keymaps over to which-key. 

I can take a crack at a PR if that would remotely helpful!

**Comment by redyf** [comment]
That would be great, I appreciate your initiative :smile:

**Comment by mcgilly17** [comment]
On it! Will take a crack and raise a PR. Expect it shortly, just need to workout how to test it first!

**Comment by mcgilly17** [comment]
PR raised, I am still quite new to nix / nixvim so there is a non-zero chance I screwed something up. Will make any changes / fixes you wish!

**Comment by redyf** [comment]
> PR raised, I am still quite new to nix / nixvim so there is a non-zero chance I screwed something up. Will make any changes / fixes you wish!

No worries, the best way to learn is with practice 😄
I'll take a look at it tomorrow after work 🤝
